import type { ForeignTripData } from './schemas'
import type { DomesticTripData } from './schemas'

export const foreignDemoData: ForeignTripData = {
  employerName: 'Példa Kft.',
  employerAddress: '',
  employerTaxNumber: '',
  employeeName: 'Kovács János',
  employeePosition: 'Projektmenedzser',
  employeeAddress: '',
  employeeBirthPlaceDate: '',
  employeeMotherName: '',
  employeeTaxId: '',
  purposeText: 'Ügyfélmegbeszélés és együttműködési tárgyalás.',
  issuedDate: new Date().toISOString().slice(0, 10),
  orderNumber: '',
  orderedByName: 'Példa Kft. igazgató',
  signatures: {},
  attachmentsCount: 1,
  country: 'Németország',
  cityOrViszonylat: 'Berlin',
  startDate: new Date().toISOString().slice(0, 10),
  endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
  travelModeOut: 'Repülőgép',
  travelModeBack: 'Repülőgép',
  localTravelEligible: false,
  perdiemEligible: false,
  costs: {
    flightTickets: [
      { docNo: 'REP-001', place: 'Budapest–Berlin', date: new Date().toISOString().slice(0, 10), legalTitle: 'Repülőjegy', currency: 'EUR', amount: 180 },
    ],
    accommodation: [],
    otherCosts: [],
  },
}

export const domesticDemoData: DomesticTripData = {
  employerName: 'Példa Kft.',
  employerAddress: '',
  employerTaxNumber: '',
  employeeName: 'Kovács János',
  employeePosition: 'Projektmenedzser',
  employeeAddress: '',
  employeeBirthPlaceDate: '',
  employeeMotherName: '',
  employeeTaxId: '',
  purposeText: 'Regionális iroda látogatás.',
  issuedDate: new Date().toISOString().slice(0, 10),
  orderNumber: '',
  orderedByName: 'Példa Kft. igazgató',
  signatures: {},
  attachmentsCount: 1,
  cityOrViszonylat: 'Debrecen',
  startDate: new Date().toISOString().slice(0, 10),
  endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
  travelMode: 'Vonat',
  plateNumber: '',
  fuelType: '',
  tripRows: [],
  perdiemEligible: false,
  costs: { items: [{ docNo: 'V-1', description: 'Vonatjegy oda-vissza', currency: 'HUF', amount: 12500 }] },
}
